#pragma once

#include <string_view>

// Generated by scripts/icons.py from content/icons/icons.json: each icon's
// character as UTF-8, drawn by the icons font (a fallback after the
// text's own fonts). Do not edit.
namespace sn::icon
{
inline constexpr const char* LASER_S = "\xee\x80\x80";             // Pulse laser
inline constexpr const char* PLASMA_S = "\xee\x80\x81";            // Plasma gun
inline constexpr const char* SHIELD_BOOSTER_S = "\xee\x80\x82";    // Shield booster
inline constexpr const char* CAPACITOR_BATTERY_S = "\xee\x80\x83"; // Capacitor battery
inline constexpr const char* PLASMA_CHARGE_S = "\xee\x80\x84";     // Plasma charge
inline constexpr const char* LANCER = "\xee\x80\x85";              // Lancer
inline constexpr const char* RAIDER = "\xee\x80\x86";              // Raider
inline constexpr const char* MINE = "\xee\x80\x87";                // Metal mine
inline constexpr const char* EXTRACTOR = "\xee\x80\x88";           // He-3 extractor
inline constexpr const char* FAB = "\xee\x80\x89";                 // Chip fab
inline constexpr const char* DEPOT = "\xee\x80\x8a";               // Depot
inline constexpr const char* COMMAND = "\xee\x80\x8b";             // Command center
inline constexpr const char* METAL = "\xee\x80\x8c";               // Metal
inline constexpr const char* HE3 = "\xee\x80\x8d";                 // Helium-3
inline constexpr const char* CHIPS = "\xee\x80\x8e";               // Chips
inline constexpr const char* COMMAND_POINTS = "\xee\x80\x8f";      // Command points
inline constexpr const char* EM = "\xee\x80\x90";                  // EM
inline constexpr const char* THERMAL = "\xee\x80\x91";             // Thermal
inline constexpr const char* KINETIC = "\xee\x80\x92";             // Kinetic
inline constexpr const char* EXPLOSIVE = "\xee\x80\x93";           // Explosive
inline constexpr const char* SLOT_EXTERNAL = "\xee\x80\x94";       // External slot
inline constexpr const char* SLOT_INTERNAL = "\xee\x80\x95";       // Internal slot
inline constexpr const char* POWER = "\xee\x80\x96";               // Power
inline constexpr const char* MASS = "\xee\x80\x97";                // Mass
inline constexpr const char* SPEED = "\xee\x80\x98";               // Speed
inline constexpr const char* THRUST = "\xee\x80\x99";              // Thrust
inline constexpr const char* ACCEL = "\xee\x80\x9a";               // Acceleration
inline constexpr const char* TURN = "\xee\x80\x9b";                // Turn
inline constexpr const char* HULL = "\xee\x80\x9c";                // Hull
inline constexpr const char* SHIELD = "\xee\x80\x9d";              // Shield
inline constexpr const char* REGEN = "\xee\x80\x9e";               // Shield regen
inline constexpr const char* THRESHOLD = "\xee\x80\x9f";           // Shield threshold
inline constexpr const char* RESIST = "\xee\x80\xa0";              // Resistances
inline constexpr const char* CAPACITOR = "\xee\x80\xa1";           // Capacitor
inline constexpr const char* SLOTS = "\xee\x80\xa2";               // Slots
inline constexpr const char* SCANNER = "\xee\x80\xa3";             // Scanner
inline constexpr const char* CARGO = "\xee\x80\xa4";               // Cargo
inline constexpr const char* DAMAGE = "\xee\x80\xa5";              // Damage
inline constexpr const char* RANGE = "\xee\x80\xa6";               // Range
inline constexpr const char* FIRERATE = "\xee\x80\xa7";            // Fire rate
inline constexpr const char* MAGAZINE = "\xee\x80\xa8";            // Magazine
inline constexpr const char* RELOAD = "\xee\x80\xa9";              // Reload
inline constexpr const char* ENERGY = "\xee\x80\xaa";              // Energy
inline constexpr const char* SHOT = "\xee\x80\xab";                // Shot speed
inline constexpr const char* AMMO = "\xee\x80\xac";                // Ammo
inline constexpr const char* BATCH = "\xee\x80\xad";               // Batch
inline constexpr const char* COLONY = "\xee\x80\xae";              // Colony
inline constexpr const char* MAP = "\xee\x80\xaf";                 // Star map
inline constexpr const char* LAUNCH = "\xee\x80\xb0";              // Launch
inline constexpr const char* GROW = "\xee\x80\xb1";                // Growth
inline constexpr const char* TROPHY = "\xee\x80\xb2";              // Trophy
inline constexpr const char* PLAY = "\xee\x80\xb3";                // Play
inline constexpr const char* STAR = "\xee\x80\xb4";                // Stella Nova
inline constexpr const char* UPGRADE = "\xee\x80\xb5";             // Upgrade
inline constexpr const char* REPAIR = "\xee\x80\xb6";              // Repair
inline constexpr const char* BUILD = "\xee\x80\xb7";               // Build
inline constexpr const char* FLEET = "\xee\x80\xb8";               // Fleet
inline constexpr const char* NODE_PIRATES = "\xee\x80\xb9";        // Pirates
inline constexpr const char* NODE_RICH = "\xee\x80\xba";           // Rich field
inline constexpr const char* CLEARED = "\xee\x80\xbb";             // Cleared
inline constexpr const char* LOCKED = "\xee\x80\xbc";              // Locked
inline constexpr const char* GUEST = "\xee\x80\xbd";               // Guest

// Every icon by its id (the catalog's, where it has one).
struct Code
{
	const char* id;
	const char* text;
};

inline constexpr Code ALL[] = {
	{"laser_s", "\xee\x80\x80"},
	{"plasma_s", "\xee\x80\x81"},
	{"shield_booster_s", "\xee\x80\x82"},
	{"capacitor_battery_s", "\xee\x80\x83"},
	{"plasma_charge_s", "\xee\x80\x84"},
	{"lancer", "\xee\x80\x85"},
	{"raider", "\xee\x80\x86"},
	{"mine", "\xee\x80\x87"},
	{"extractor", "\xee\x80\x88"},
	{"fab", "\xee\x80\x89"},
	{"depot", "\xee\x80\x8a"},
	{"command", "\xee\x80\x8b"},
	{"metal", "\xee\x80\x8c"},
	{"he3", "\xee\x80\x8d"},
	{"chips", "\xee\x80\x8e"},
	{"command_points", "\xee\x80\x8f"},
	{"em", "\xee\x80\x90"},
	{"thermal", "\xee\x80\x91"},
	{"kinetic", "\xee\x80\x92"},
	{"explosive", "\xee\x80\x93"},
	{"slot_external", "\xee\x80\x94"},
	{"slot_internal", "\xee\x80\x95"},
	{"power", "\xee\x80\x96"},
	{"mass", "\xee\x80\x97"},
	{"speed", "\xee\x80\x98"},
	{"thrust", "\xee\x80\x99"},
	{"accel", "\xee\x80\x9a"},
	{"turn", "\xee\x80\x9b"},
	{"hull", "\xee\x80\x9c"},
	{"shield", "\xee\x80\x9d"},
	{"regen", "\xee\x80\x9e"},
	{"threshold", "\xee\x80\x9f"},
	{"resist", "\xee\x80\xa0"},
	{"capacitor", "\xee\x80\xa1"},
	{"slots", "\xee\x80\xa2"},
	{"scanner", "\xee\x80\xa3"},
	{"cargo", "\xee\x80\xa4"},
	{"damage", "\xee\x80\xa5"},
	{"range", "\xee\x80\xa6"},
	{"firerate", "\xee\x80\xa7"},
	{"magazine", "\xee\x80\xa8"},
	{"reload", "\xee\x80\xa9"},
	{"energy", "\xee\x80\xaa"},
	{"shot", "\xee\x80\xab"},
	{"ammo", "\xee\x80\xac"},
	{"batch", "\xee\x80\xad"},
	{"colony", "\xee\x80\xae"},
	{"map", "\xee\x80\xaf"},
	{"launch", "\xee\x80\xb0"},
	{"grow", "\xee\x80\xb1"},
	{"trophy", "\xee\x80\xb2"},
	{"play", "\xee\x80\xb3"},
	{"star", "\xee\x80\xb4"},
	{"upgrade", "\xee\x80\xb5"},
	{"repair", "\xee\x80\xb6"},
	{"build", "\xee\x80\xb7"},
	{"fleet", "\xee\x80\xb8"},
	{"node_pirates", "\xee\x80\xb9"},
	{"node_rich", "\xee\x80\xba"},
	{"cleared", "\xee\x80\xbb"},
	{"locked", "\xee\x80\xbc"},
	{"guest", "\xee\x80\xbd"},
};

// The icon's character, or "" when there is none of that id.
inline const char* Find(std::string_view id)
{
	for (const Code& code : ALL)
	{
		if (id == code.id)
			return code.text;
	}
	return "";
}
} // namespace sn::icon
